title: Amit's Blog
email: amitgupta15@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sharing and learning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://amitgupta15.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: amitgupta15
github_username:  amitgupta15
linked_in_username: amitgupta15

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  
social:
  - title: twitter
    url: https://twitter.com/amitgupta15
  - title: github
    url: https://github.com/amitgupta15
  - title: linkedin
    url: https://www.linkedin.com/in/amitgupta15/
  - title: stack-overflow
    url: https://stackoverflow.com/users/3597607/amit-g